### ISSUE TITLE
Mirocana Alpha sequence.py error ( SyntaxError: invalid syntax (because of "{**kwargs}"). )

### ISSUE THREAD

**Issue by alexandruchirita4192** [mirocana/alpha#1]
I found the following error while trying to create a new trading strategy following the https://mirocana.com/alpha/ guide.

The workaround I found the this error is changing line 20 in file sequence.py which has
**`"self.context = {**kwargs}"`**
into
**`"self.context = kwargs"`**
(screenshot with vim: https://ibb.co/kXZjvR - another way to put it, keep only what is underlined with blue)

This error didn't happen on all my linux systems (not allowing this kind of code might be a python version issue?).

The error with stack trace:
```
Traceback (most recent call last):
  File "strategies/testing.py", line 3, in <module>
    from sequence import DeltaMQB
  File "/home/noname/alpha/sequence.py", line 20
    self.context = {**kwargs}
                    ^
SyntaxError: invalid syntax
```

**Comment by alexandruchirita4192** [comment]
Proposed commit:
https://github.com/alexandruchirita4192/alpha/commit/3610ca8b0f487401596daf7f8684a647e2b2a52b
